### ISSUE TITLE
PTT Interface

### ISSUE THREAD

**Issue by bobh** [hessu/aprs-specs#2]
Consider a pull request to add a PTT interface BLE characteristic.
Some modem waveforms do not lend themselves to a derived PTT (tx keyline) as easily as FSK.
Key delay to data valid could still be specified in the KISS parameters to give the PA time to power up/antenna match/TDMA slot, etc. .

**Comment by hessu** [comment]
Hi,

I'm not sure what do you mean, please explain with some more detail?

The KISS over BLE specification allows transmitting arbitrary KISS frames, including command/control frames, which are described here: https://www.ax25.net/kiss.aspx - command 1 adjusts txdelay, and I suppose that it could be used with other modes just as well.

**Comment by bobh** [comment]
It’s been awhile, but what I was thinking was a separate BLE characteristic added to the spec to turn PTT on/off under control of the modem. So you are saying that isn’t needed because a preamble can be arbitrarily long and thus would work independent of the waveform modulation type (e.g. with smooth phase transitions or something more exotic). 
OK. I didn’t a have problematic modulation technique in mind.
Thank you for your consideration.

**Comment by hessu** [comment]
In the "regular" Bell 202 AFSK modem, as well as 9600 bit/s G3RUH modems, the preamble is configured on the modem and generated there. It is under full control of the modem.

The TCP KISS application is not sending a preamble; it is sending the data contents of the frame. The modem behind the BLE link is generating the waveform and controlling PTT.
